server:
  port: 9001
spring:
  application:
    name: user-auth
  redis:
    host: 47.100.46.113
    port: 6379
    password:
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.100.46.113:3307/changgou_oauth?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true&serverTimezone=UTC
    username: root
    password: 123456
  main:
    allow-bean-definition-overriding: true
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka
auth:
  ttl: 3600  #token存储到redis的过期时间
  clientId: changgou #客户端的id
  clientSecret: changgou #客户端的密钥
  cookieDomain: localhost
  cookieMaxAge: -1
#本地证书和密钥以及证书密码配置
encrypt:
  key-store:
    location: classpath:/changgou.jks #证书路径配置
    secret: changgou #密钥
    alias: changgou #证书的别名
    password: changgou #证书的密码